### ISSUE TITLE
Composer package

### ISSUE THREAD

**Issue by XhmikosR** [workingconcept/versioneer-craft-plugin#2]
Hello, can you publish this on composer?

**Comment by mattstein** [comment]
This is a Craft 2 plugin @XhmikosR, can you help me understand what you're looking to accomplish?

**Comment by XhmikosR** [comment]
Oops, sorry, I thought it was for v3.

**Comment by mattstein** [comment]
No problem! I'll take your request as a reminder to port it if I have time ;)

**Comment by XhmikosR** [comment]
Yeah, I found this quite useful judging from the screenshots :)
